name: CI/CD
on: 
    push:
        branches: [master, main]

jobs:
    artifacts:
        name: Create artifact
        runs-on: ubuntu-latest
        environment:
            name: Production
        steps:
        -   name: Checkout
            uses: actions/checkout@v4
        -   name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: '8.0.x'
                dotnet-quality: 'preview'

        -   name: App.Config
            uses: microsoft/variable-substitution@v1
            with:
                files: 'Application/App.Release.config'
            env:
                connectionString: ${{ secrets.CONNECTION_STRING }}

        -   name: Publish
            run: dotnet publish Application/Application.csproj -r linux-x64 -c Release

        -   name: Upload Publish Artifact
            uses: actions/upload-artifact@v3
            with:
                name: SteamBot
                path: Application/bin/Release/net7.0/linux-x64/publish/

