name: test-action
on: 
  push:
    branches: [master, main]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      - name: Restore dependencies
        run:  dotnet restore
      - name: Build
        run: dotnet build ./Application/Application.csproj --no-restore
